export const REQUEST_FACT='REQUEST_FACT'
export const GET_FACT_FAILURE='GET_FACT_FAILURE'
export const GET_FACT_SUCCESS='GET_FACT_SUCCESS'

export const REQUEST_BREEDS='REQUEST_BREEDS'
export const GET_BREEDS_FAILURE='GET_BREEDS_FAILURE'
export const GET_BREEDS_SUCCESS='GET_BREEDS_SUCCESS'